cd $(dirname $0)
export PATH=$PATH:$PWD/node_modules/.bin

echo "{/* Auto-generated by build.sh */}" > lib/theme-script.astro
echo "<script is:inline>" >> lib/theme-script.astro
esbuild --minify --bundle lib/theme-script.ts >> lib/theme-script.astro
echo "</script>" >> lib/theme-script.astro

astro build 
